vim.keymap.set("n", "<C-f>n", function()
    pcall(function()
        vim.cmd.cnext()
    end)
end, { desc = "go to [n]ext quickfix" })
vim.keymap.set("n", "<C-f>p", function()
    pcall(function()
        vim.cmd.cprev()
    end)
end, { desc = "go to [p]revious quickfix" })
vim.keymap.set("n", "<C-f>c", vim.cmd.cclose, { desc = "[c]lose quickfix" })
vim.keymap.set("n", "<C-f>o", vim.cmd.copen, { desc = "[o]pen quickfix" })
